# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=200, verbose_name='Apellido')),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('id_number', models.CharField(max_length=200, verbose_name='Cedula')),
                ('password', models.CharField(max_length=200, verbose_name='Password')),
                ('nickname', models.CharField(max_length=200, verbose_name='Nickname')),
                ('type_Client', models.IntegerField(default=0, verbose_name='Valor')),
                ('points', models.IntegerField(default=3000, verbose_name='Saldo')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
                'verbose_name': 'Usuario',
            },
        ),
    ]
