# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaccion', 'verbose_name_plural': 'Transacciones'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='monto',
            field=models.IntegerField(null=True, verbose_name=b'Monto de transferencia'),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='receptor',
        ),
        migrations.AddField(
            model_name='transaction',
            name='receptor',
            field=models.ManyToManyField(related_name='cliente2', to='client.Client'),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='remitente',
        ),
        migrations.AddField(
            model_name='transaction',
            name='remitente',
            field=models.ManyToManyField(related_name='cliente1', to='client.Client'),
        ),
    ]
