# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20161214_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='fecha',
            field=models.DateTimeField(verbose_name=b'Fecha y hora de transaccion'),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='receptor',
        ),
        migrations.AddField(
            model_name='transaction',
            name='receptor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente2', to='client.Client'),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='remitente',
        ),
        migrations.AddField(
            model_name='transaction',
            name='remitente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente1', to='client.Client'),
        ),
    ]
