# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20161214_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='concepto',
            field=models.CharField(max_length=200, verbose_name='Concepto'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha y hora de transaccion'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id_transaction',
            field=models.IntegerField(verbose_name='Numero de transaccion'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='monto',
            field=models.IntegerField(null=True, verbose_name='Monto de transferencia'),
        ),
    ]
