# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20161215_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nickname',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nickname'),
        ),
    ]
