# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 22:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20161215_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='concepto',
            field=models.CharField(max_length=200, null=True, verbose_name='Concepto'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha y hora de transaccion'),
        ),
    ]
