# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 22:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20161215_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha y hora de transaccion'),
        ),
    ]
